name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # 每次你推送到主分支时触发
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite 打包后的文件夹
